/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ContactMessage = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'processing' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'productId' : IDL.Nat,
  'address' : IDL.Text,
  'timestamp' : IDL.Int,
  'quantity' : IDL.Nat,
  'phone' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'stockQuantity' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Record({ 'id' : IDL.Nat })],
      [],
    ),
  'deleteContactMessage' : IDL.Func([IDL.Nat], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getAllContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactMessage' : IDL.Func([IDL.Nat], [ContactMessage], ['query']),
  'getMyRole' : IDL.Func([], [UserRole], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchContactMessages' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ContactMessage)],
      ['query'],
    ),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  'updateProduct' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ContactMessage = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'processing' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'productId' : IDL.Nat,
    'address' : IDL.Text,
    'timestamp' : IDL.Int,
    'quantity' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'stockQuantity' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Record({ 'id' : IDL.Nat })],
        [],
      ),
    'deleteContactMessage' : IDL.Func([IDL.Nat], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getAllContactMessages' : IDL.Func(
        [],
        [IDL.Vec(ContactMessage)],
        ['query'],
      ),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactMessage' : IDL.Func([IDL.Nat], [ContactMessage], ['query']),
    'getMyRole' : IDL.Func([], [UserRole], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchContactMessages' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ContactMessage)],
        ['query'],
      ),
    'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
    'updateProduct' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };